FPGA_CONTROL_MAIN_FILE = test.cpp
FPGA_CONTROL_SOURCES = $(FPGA_CONTROL_MAIN_FILE)
FPGA_CONTROL_OBJECTS = $(FPGA_CONTROL_SOURCES:.cpp=.o)
FPGA_CONTROL_EXECUTABLE = $(OUTPUT_DIR)/$(FPGA_CONTROL_MAIN_FILE:%.cpp=%)

DEPS += $(FPGA_CONTROL_SOURCES:%.cpp=%.d) 
EXECUTABLES += $(FPGA_CONTROL_EXECUTABLE)
CLEANUP += $(FPGA_CONTROL_EXECUTABLE) $(FPGA_CONTROL_OBJECTS)

$(FPGA_CONTROL_EXECUTABLE): $(C_OBJECTS) $(CPP_OBJECTS) $(FPGA_CONTROL_OBJECTS)
	@echo Linking...
	@$(CPP)  $(CPP_OBJECTS) $(C_OBJECTS) $(FPGA_CONTROL_OBJECTS) -o $@ $(LDFLAGS)
